import * as XLSX from 'xlsx'
import { supabase } from '../lib/supabase'

const columns = ['الاسم العربي','English Name','تاريخ انتهاء الصلاحية','المادة الفعالة','التركيز','نوع الصنف','الشكل الدوائي','التصنيف','عدد العلب','الوحدة المتوسطة','عدد الوحدات المتوسطة/العلبة','الوحدة الصغيرة','عدد الوحدات الصغيرة/الوحدة المتوسطة','الباركود','السعر','سعر الشراء']
function inventoryQuantity(product) { return Number(product.inventory?.[0]?.quantity_smallest_unit || 0) }
function exportRow(product, isAdmin) { return { 'الاسم العربي': product.name || '', 'English Name': product.name_en || '', 'تاريخ انتهاء الصلاحية': product.expiry_date || '', 'المادة الفعالة': product.active_ingredient || '', 'التركيز': product.concentration || '', 'نوع الصنف': product.drug_type || '', 'الشكل الدوائي': product.shape || '', 'التصنيف': product.classification || '', 'عدد العلب': inventoryQuantity(product), 'الوحدة المتوسطة': product.unit_medium || '', 'عدد الوحدات المتوسطة/العلبة': product.unit_large_to_medium || 1, 'الوحدة الصغيرة': product.unit_small || '', 'عدد الوحدات الصغيرة/الوحدة المتوسطة': product.unit_medium_to_small || 1, 'الباركود': product.qr_code || '', 'السعر': product.default_sale_price ?? '', 'سعر الشراء': isAdmin ? (product.purchase_price ?? '') : '' } }
async function loadAllProducts(isAdmin = false) { const result = []; for (let from = 0; ; from += 1000) { const { data, error } = await supabase.from('products').select(`name,name_en,expiry_date,active_ingredient,concentration,drug_type,shape,classification,default_sale_price,qr_code,unit_large,unit_large_to_medium,unit_medium,unit_medium_to_small,unit_small,inventory(quantity_smallest_unit)${isAdmin ? ',product_costs(purchase_price)' : ''}`).order('name').range(from, from + 999); if (error) throw error; result.push(...(data || []).map(row => ({ ...row, purchase_price: row.isAdmin ? (row.product_costs?.[0]?.purchase_price ?? null) : null }))); if (!data || data.length < 1000) return result } }
function download(rows, sheetName, fileName) { const sheet = XLSX.utils.json_to_sheet(rows, { header: columns }); sheet['!cols'] = columns.map(() => ({ wch: 22 })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, sheetName); XLSX.writeFile(book, fileName) }
export async function exportInventory(isAdmin = false) { download((await loadAllProducts(isAdmin)).map(product => exportRow(product, isAdmin)), 'المخزون', 'مخزون_الصيدلية.xlsx') }
export function downloadImportTemplate() { download([{ 'الاسم العربي':'أوجمنتين', 'English Name':'Augmentin', 'تاريخ انتهاء الصلاحية':'2028-10-01', 'المادة الفعالة':'Amoxicillin', 'التركيز':'1 g', 'نوع الصنف':'medicine', 'الشكل الدوائي':'tablet', 'التصنيف':'مضاد حيوي', 'عدد العلب':5, 'الوحدة المتوسطة':'strip', 'عدد الوحدات المتوسطة/العلبة':3, 'الوحدة الصغيرة':'piece', 'عدد الوحدات الصغيرة/الوحدة المتوسطة':10, 'الباركود':'', 'السعر':40, 'سعر الشراء':'' }], 'نموذج استيراد', 'نموذج_استيراد_أصناف_الصيدلية.xlsx') }
function get(row, ...names) { const keys = Object.keys(row); for (const name of names) { const key = keys.find(item => item.trim().toLowerCase() === name.toLowerCase()); if (key && row[key] !== '') return row[key] } return '' }
function dateValue(value) { if (!value) return ''; if (typeof value === 'number') { const parsed = XLSX.SSF.parse_date_code(value); return parsed ? `${parsed.y}-${String(parsed.m).padStart(2,'0')}-${String(parsed.d).padStart(2,'0')}` : '' } const text = String(value).trim(); if (/^\d{4}-\d{1,2}-\d{1,2}$/.test(text)) return text.split('-').map((part, index) => index === 0 ? part : part.padStart(2,'0')).join('-'); const parts = text.split('/'); if (parts.length === 3) return `${parts[2]}-${parts[1].padStart(2,'0')}-${parts[0].padStart(2,'0')}`; return '' }
export async function parseImportFile(file) { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json(sheet, { defval: '' }); if (!rows.length) throw new Error('الملف فارغ.'); return rows.map((row, index) => { const name = String(get(row, 'الاسم العربي', 'اسم الصنف', 'الاسم', 'name')).trim(); const boxes = Number(get(row, 'عدد العلب', 'الكمية', 'الكمية (عدد علب)') || 0); const medium = Number(get(row, 'عدد الوحدات المتوسطة/العلبة') || 1); const small = Number(get(row, 'عدد الوحدات الصغيرة/الوحدة المتوسطة') || 1); const errors = []; if (!name) errors.push('اسم الصنف مفقود'); if (!Number.isFinite(boxes) || boxes < 0) errors.push('الكمية غير صحيحة'); if (!Number.isFinite(medium) || medium < 1 || !Number.isFinite(small) || small < 1) errors.push('تعبئة الوحدات غير صحيحة'); const cost = get(row, 'سعر الشراء'); return { rowNumber: index + 2, valid: errors.length === 0, errors, form: { name, nameEn: String(get(row, 'English Name', 'الاسم بالإنجليزي') || ''), drugType: String(get(row, 'نوع الصنف') || 'other'), shape: String(get(row, 'الشكل الدوائي', 'الشكل') || 'other'), classification: String(get(row, 'التصنيف') || ''), supplier: String(get(row, 'المورد') || ''), activeIngredient: String(get(row, 'المادة الفعالة') || ''), concentration: String(get(row, 'التركيز') || ''), retailAllowed: true, hasStrip: Boolean(get(row, 'الوحدة الصغيرة')), largeToMedium: medium, mediumToSmall: small, salePrice: get(row, 'السعر', 'سعر البيع') === '' ? '' : Number(get(row, 'السعر', 'سعر البيع')), purchasePrice: cost === '' ? '' : Number(cost), boxesQuantity: boxes, leftoverMedium: 0, leftoverSmall: 0, expiryDate: dateValue(get(row, 'تاريخ انتهاء الصلاحية', 'تاريخ الانتهاء')), minThreshold: 0, qrCode: String(get(row, 'الباركود') || '') } } }) }
