import { useEffect, useMemo, useState } from 'react'
import { createCustomer, loadCustomerWorkspace } from '../services/customerService'

export default function CustomersPage({ userId }) {
  const [workspace, setWorkspace] = useState({ customers: [], ledger: [], sales: [], followups: [] }); const [query, setQuery] = useState(''); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState({ name: '', phone: '', category: 'regular', credit_limit: '', notes: '' }); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true)
  async function load() { setLoading(true); try { setWorkspace(await loadCustomerWorkspace()) } catch (error) { setMessage(`تعذر تحميل العملاء: ${error.message || ''}`) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const balances = useMemo(() => workspace.customers.map(customer => { const balance = workspace.ledger.filter(row => row.customer_id === customer.id).reduce((sum, row) => sum + Number(row.amount || 0), 0); const purchases = workspace.sales.filter(row => row.customer_id === customer.id).reduce((sum, row) => sum + Number(row.sale_price || 0), 0); return { ...customer, balance, purchases } }), [workspace])
  const filtered = balances.filter(customer => `${customer.name} ${customer.phone || ''} ${customer.area || ''}`.toLowerCase().includes(query.toLowerCase())).slice(0, 200)
  async function submit(event) { event.preventDefault(); if (!form.name.trim()) return setMessage('اسم العميل مطلوب.'); try { await createCustomer({ ...form, name: form.name.trim(), credit_limit: form.credit_limit === '' ? null : Number(form.credit_limit) }); setForm({ name: '', phone: '', category: 'regular', credit_limit: '', notes: '' }); setFormOpen(false); setMessage('تمت إضافة العميل بنجاح.'); await load() } catch (error) { setMessage(`تعذر حفظ العميل: ${error.message || ''}`) } }
  return <section className="content"><div className="page-heading"><div><span className="eyebrow">React migration · CRM</span><h2>العملاء والـCRM</h2><p>بيانات العملاء والمديونيات ونشاط الشراء والمتابعات في طبقة منفصلة.</p></div><button className="primary-button add-button" onClick={() => setFormOpen(value => !value)}>{formOpen ? 'إخفاء النموذج' : '+ عميل جديد'}</button></div>{formOpen && <form className="product-form customer-form" onSubmit={submit}><div className="form-grid"><label>اسم العميل *<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>الهاتف<input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></label><label>التصنيف<select value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}><option value="regular">عادي</option><option value="clinic">عيادة</option><option value="pharmacy">صيدلية</option><option value="wholesale">جملة</option></select></label><label>حد الائتمان<input type="number" min="0" value={form.credit_limit} onChange={event => setForm({ ...form, credit_limit: event.target.value })} /></label><label className="full-span">ملاحظات<textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} rows="2" /></label></div><button className="primary-button">حفظ العميل</button></form>}<div className="crm-stats"><div className="stat-card"><strong>{workspace.customers.length}</strong><span>إجمالي العملاء</span></div><div className="stat-card"><strong>{balances.filter(item => item.balance > 0).length}</strong><span>عليهم مديونية</span></div><div className="stat-card"><strong>{workspace.followups.filter(item => item.status !== 'done').length}</strong><span>متابعات مفتوحة</span></div></div><div className="toolbar"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث باسم العميل أو الهاتف أو المنطقة..." /><span>{loading ? 'جاري التحميل...' : `${filtered.length} عميل`}</span></div>{message && <div className="success-text">{message}</div>}<div className="table-card"><table><thead><tr><th>العميل</th><th>الهاتف</th><th>التصنيف</th><th>إجمالي الشراء</th><th>الرصيد</th><th>الحالة</th></tr></thead><tbody>{filtered.map(customer => <tr key={customer.id}><td><b>{customer.name}</b><small className="table-subtext">{customer.area || customer.address || 'بدون عنوان'}</small></td><td>{customer.phone || '—'}</td><td>{customer.category || 'عادي'}</td><td>{customer.purchases.toFixed(2)} ج.م</td><td className={customer.balance > 0 ? 'debt-value' : ''}>{customer.balance.toFixed(2)} ج.م</td><td><span className={`status-pill ${customer.status === 'inactive' ? 'danger' : customer.balance > 0 ? 'warning' : 'ok'}`}>{customer.status === 'inactive' ? 'غير نشط' : customer.balance > 0 ? 'مديون' : 'منتظم'}</span></td></tr>)}</tbody></table>{!loading && !filtered.length && <div className="empty-state">لا توجد نتائج.</div>}</div></section>
}
