import { useEffect, useState } from 'react'
import { loadShortages } from '../services/stockOperationsService'

function downloadCsv(rows) { const header = ['الصنف','المورد','الكمية','الحد الأدنى','الصلاحية','الحالة']; const lines = [header, ...rows.map(row => [row.name, row.supplier || 'غير مصنف', row.quantity, row.threshold || 'غير مصنف', row.expiry_date || 'غير مصنف', row.isOut ? 'نافد' : row.isLow ? 'منخفض' : row.expired ? 'منتهي' : 'صلاحية قريبة'])].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')); const blob = new Blob([`\ufeff${lines.join('\n')}`], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'تقرير_النواقص_والصلاحية.csv'; link.click(); URL.revokeObjectURL(link.href) }
export default function ShortagesPage() {
  const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const [supplier, setSupplier] = useState('all'); const [severity, setSeverity] = useState('all'); const [expiry, setExpiry] = useState('all'); const [sort, setSort] = useState('name'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { setLoading(true); setError(''); try { setRows(await loadShortages({ search: query, supplier, severity, expiry, sort })) } catch (err) { setError(`تعذر تحميل النواقص والصلاحية: ${err.message || ''}`) } finally { setLoading(false) } }
  useEffect(() => { load().catch(() => {}) }, [query, supplier, severity, expiry, sort])
  const suppliers = [...new Set(rows.map(row => row.supplier).filter(Boolean))].sort()
  return <section className="content"><div className="page-heading"><div><span className="eyebrow">React migration · النواقص والصلاحية</span><h2>النواقص والصلاحية</h2><p>الأصناف النافدة والمنخفضة والمنتهية أو التي تنتهي خلال خمسة شهور.</p></div><div className="stat-card"><strong>{rows.length}</strong><span>نتيجة</span></div></div><div className="toolbar inventory-filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث باسم الصنف..." /><select value={supplier} onChange={e => setSupplier(e.target.value)}><option value="all">كل الموردين</option><option value="uncategorized">غير مصنف</option>{suppliers.map(value => <option key={value} value={value}>{value}</option>)}</select><select value={severity} onChange={e => setSeverity(e.target.value)}><option value="all">كل درجات النقص</option><option value="out">نافد</option><option value="low">منخفض</option><option value="uncategorized">غير مصنف</option></select><select value={expiry} onChange={e => setExpiry(e.target.value)}><option value="all">كل الصلاحيات</option><option value="near">تنتهي خلال 5 شهور</option><option value="expired">منتهية</option><option value="uncategorized">غير مصنف</option></select><select value={sort} onChange={e => setSort(e.target.value)}><option value="name">A-Z / أ-ي</option><option value="za">Z-A / ي-أ</option><option value="newest">الأحدث أولًا</option></select><button className="secondary-button" onClick={() => downloadCsv(rows)}>تصدير CSV</button><button className="secondary-button" onClick={() => window.print()}>طباعة</button></div>{error && <div className="error-text">{error}</div>}<div className="table-card"><table><thead><tr><th>الصنف</th><th>المورد</th><th>الكمية</th><th>الحد الأدنى</th><th>الصلاحية</th><th>الحالة</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><b>{row.name}</b></td><td>{row.supplier || 'غير مصنف'}</td><td>{row.quantity}</td><td>{row.threshold || 'غير مصنف'}</td><td>{row.expiry_date || 'غير مصنف'}</td><td>{row.isOut ? <span className="status-pill danger">نافد</span> : row.isLow ? <span className="status-pill warning">منخفض</span> : row.expired ? <span className="status-pill danger">منتهي</span> : <span className="status-pill warning">صلاحية قريبة</span>}</td></tr>)}</tbody></table>{!loading && !rows.length && <div className="empty-state">لا توجد نتائج.</div>}</div></section>
}
